---
- hosts: all

  tasks:
    - name: create Documents directory
      file:
        path: "{{ path_directorio }}"
        state: directory

    - name: create file into Documents directory 
      file:
        path: "{{ path_directorio }}{{ file_name }}"
        state: touch
        mode: "{{ permissions }}"
